openapi: 3.0.2

info:
  title: Todo API
  description: <b>Todoを管理するAPI</b>
  version: 1.0.0

servers: 
 - url: http://localhost:9000
tags:
 - name: task
   description: タスク関連API
 - name: user
   description: ユーザー情報API
paths: 
  /task:
    post:
      tags:
        - task
      summary: タスク追加
      description:
        タスクを追加API
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateTaskRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTaskResponse'
    get:
      tags:
        - task
      summary: タスク一覧取得
      description:
        タスク一覧を取得API
      requestBody:
        description: Request Body
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/GetTasksRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTasksResponse'
  /task/task_id/{taskID}:
    get:
      tags:
        - task
      summary: タスク取得
      description: タスク取得API
      parameters:
        - $ref: '#/components/parameters/taskID'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTaskResponse'

components:
  schemas:
    CreateTaskRequest:
      type: object
      properties:
        user_id:
          type: string
          example: "1"
          description: ユーザーID
        title:
          type: string
          example: "掃除"
          description: タスクのタイトル
        description:
          type: string
          example: "掃除機をかける"
          description: タスクの概要
    CreateTaskResponse:
      type: object
      properties:
        task_id:
          type: string
          example: "0e8aeae4-0548-4929-9a70-69d216c70811"
          description: 保存されたタスクのID
    GetTasksRequest:
      type: object
      properties:
        user_id:
          type: string
          example: "1"
    GetTasksResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/GetTaskResponse'
    GetTaskResponse:
      type: object
      properties:
        task_id:
          type: string
          example: "0e8aeae4-0548-4929-9a70-69d216c70811"
          description: タスクID
        title:
          type: string
          example: "掃除"
          description: タスクのタイトル
        description:
          type: string
          example: "掃除機をかける"
          description: タスクの概要
        created_at:
          type: string
          description: タスク作成時間
          format: date-time
        updated_at:
          type: string
          description: タスク更新時間
          format: date-time
  parameters:
    taskID:
      name: taskID
      in: path
      required: true
      description: taskID
      schema:
        type: string
